export const PERMISSION_KEYS = [
  'users:read',
  'users:create',
  'users:update',
  'users:deactivate',
  'users:assign_roles',
  'roles:read',
  'roles:manage',
  'organizations:read',
  'organizations:manage',
  'sites:read',
  'sites:create',
  'sites:update',
  'sites:delete',
  'sites:manage_members',
  'sites:manage_secrets',
  'sites:purge',
  'wordpress:read',
  'wordpress:manage',
  'gsc:read',
  'gsc:manage',
  'keywords:read',
  'keywords:manage',
  'ai:read',
  'ai:manage',
  'content:read',
  'content:manage',
  'operations:read',
  'operations:manage',
  'visibility:read',
  'visibility:manage',
  'links:read',
  'links:manage',
  'reports:read',
  'reports:manage',
  'client:access',
  'orchestration:read',
  'orchestration:manage',
  'automation:read',
  'automation:manage',
  'workqueue:read',
  'workqueue:manage',
  'knowledge:read',
  'knowledge:manage',
  'activities:read',
] as const;

export type PermissionKey = (typeof PERMISSION_KEYS)[number];

export interface PermissionDefinition {
  key: PermissionKey;
  module: string;
  description: string;
}

export const PERMISSIONS: readonly PermissionDefinition[] = [
  { key: 'users:read', module: 'users', description: 'List and view users' },
  { key: 'users:create', module: 'users', description: 'Create users' },
  { key: 'users:update', module: 'users', description: 'Update user profile and status' },
  { key: 'users:deactivate', module: 'users', description: 'Deactivate users' },
  { key: 'users:assign_roles', module: 'users', description: 'Assign and revoke user roles' },
  { key: 'roles:read', module: 'roles', description: 'List roles and the permission catalog' },
  { key: 'roles:manage', module: 'roles', description: 'Modify roles and their permissions' },
  { key: 'organizations:read', module: 'organizations', description: 'View organizations' },
  { key: 'organizations:manage', module: 'organizations', description: 'Create and update organizations' },
  { key: 'sites:read', module: 'sites', description: 'View sites (membership-scoped)' },
  { key: 'sites:create', module: 'sites', description: 'Create sites' },
  { key: 'sites:update', module: 'sites', description: 'Update sites' },
  { key: 'sites:delete', module: 'sites', description: 'Delete sites' },
  { key: 'sites:manage_members', module: 'sites', description: 'Manage site memberships' },
  { key: 'sites:manage_secrets', module: 'sites', description: 'Manage site secrets (encrypted storage)' },
  { key: 'sites:purge', module: 'sites', description: 'Permanently delete sites and all their data' },
  { key: 'wordpress:read', module: 'wordpress', description: 'View WordPress integration health and imported posts' },
  { key: 'wordpress:manage', module: 'wordpress', description: 'Run WordPress connection checks and content sync' },
  { key: 'gsc:read', module: 'gsc', description: 'View Search Console performance and opportunities' },
  { key: 'gsc:manage', module: 'gsc', description: 'Connect Search Console, run syncs and select properties' },
  { key: 'keywords:read', module: 'keywords', description: 'View keywords, clusters and URL mappings' },
  { key: 'keywords:manage', module: 'keywords', description: 'Run the keyword pipeline and approve mappings' },
  { key: 'ai:read', module: 'ai', description: 'View AI jobs, provider health and prompt registry' },
  { key: 'ai:manage', module: 'ai', description: 'Configure AI providers, run generations and manage prompts' },
  { key: 'content:read', module: 'content', description: 'View content packages and pipeline runs' },
  { key: 'content:manage', module: 'content', description: 'Run the content intelligence pipeline and approve briefs' },
  { key: 'operations:read', module: 'operations', description: 'View issues, recommendations, tasks, change log, baselines and alerts' },
  { key: 'operations:manage', module: 'operations', description: 'Manage issues, tasks, change log, snapshots and alerts' },
  { key: 'visibility:read', module: 'visibility', description: 'View AI visibility observations, metrics and trends' },
  { key: 'visibility:manage', module: 'visibility', description: 'Run visibility observations and manage prompt sets' },
  { key: 'links:read', module: 'links', description: 'View link analyses and link suggestions' },
  { key: 'links:manage', module: 'links', description: 'Run link analysis and approve, apply and verify link suggestions' },
  { key: 'reports:read', module: 'reports', description: 'View generated reports and branding settings' },
  { key: 'reports:manage', module: 'reports', description: 'Generate reports and manage white-label branding' },
  { key: 'client:access', module: 'client', description: 'Access the restricted client portal for authorized websites' },
  { key: 'orchestration:read', module: 'orchestration', description: 'View orchestration jobs and their status' },
  { key: 'orchestration:manage', module: 'orchestration', description: 'Create and dispatch n8n orchestration jobs' },
  { key: 'automation:read', module: 'automation', description: 'View per-site automation settings and job history' },
  { key: 'automation:manage', module: 'automation', description: 'Configure recurring automation and run history' },
  { key: 'workqueue:read', module: 'workqueue', description: 'View the agency work queue and saved filters' },
  { key: 'workqueue:manage', module: 'workqueue', description: 'Triage work items: assign, prioritize, review, ignore and create tasks' },
  { key: 'knowledge:read', module: 'knowledge', description: 'View the site knowledge base and its facts' },
  { key: 'knowledge:manage', module: 'knowledge', description: 'Add, edit and verify knowledge base facts' },
  { key: 'activities:read', module: 'activities', description: 'View activity logs' },
];

export const ALL_PERMISSIONS: readonly PermissionKey[] = PERMISSIONS.map((p) => p.key);
